version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: on-failure
  neuvuequeue:
    build: "."
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      NEUVUEQUEUE_MONGODB_DATABASE: neuvuequeue
      NEUVUEQUEUE_MONGODB_HOST: mongodb
      # AUTH0_DOMAIN: dev-oe-jgl7m.us.auth0.com
      # AUTH0_AUDIENCE: https://queue.neuvue.io