version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: on-failure
  neuvuequeue:
    build: "."
    ports:
      - 9005:9005
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      NEUVUEQUEUE_MONGODB_DATABASE: neuvuequeue
      NEUVUEQUEUE_MONGODB_HOST: mongodb
