version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: on-failure
    networks:
      - neuvue
  neuvuequeue:
    build: "."
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      NEUVUEQUEUE_MONGODB_DATABASE: neuvuequeue
      NEUVUEQUEUE_MONGODB_HOST: mongodb
      VIRTUAL_HOST: queue.neuvue.io
      LETSENCRYPT_HOST: queue.neuvue.io
    networks:
      - neuvue
networks:
  neuvue:
    external: true 